name: CI

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        rust:
          - stable
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - name: Run test suite
        run: cargo test
